export const girlNames = [
  "Aaliyah",
  "Aalia",
  "Aamna",
  "Aanisa",
  "Abla",
  "Ablae",
  "Abria",
  "Adiba",
  "Adila",
  "Afaf",
  "Afifa",
  "Afnan",
  "Ahlem",
  "Ahlima",
  "Aicha",
  "Aida",
  "Aimane",
  "Aisha",
  "Aissata",
  "Akila",
  "Aleya",
  "Alia",
  "Alima",
  "Almas",
  "Amal",
  "Amara",
  "Amel",
  "Amila",
  "Amina",
  "Aminata",
  "Amira",
  "Anadil",
  "Aniece",
  "Anissa",
  "Aniza",
  "Aria",
  "Asala",
  "Asil",
  "Asila",
  "Asma",
  "Asmae",
  "Assiya",
  "Aya",
  "Ayat",
  "Ayda",
  "Ayla",
  "Aylin",
  "Aziza",
  "Badia",
  "Basma",
  "Bassima",
  "Baya",
  "Bayan",
  "Bouthaina",
  "Chaima",
  "Chama",
  "Chayma",
  "Chiraz",
  "Dalila",
  "Dana",
  "Dania",
  "Daniah",
  "Darine",
  "Dhia",
  "Diala",
  "Dina",
  "Djamila",
  "Dounia",
  "Douaa",
  "Duaa",
  "Duha",
  "Ebtissam",
  "Elham",
  "Elisa",
  "Elissa",
  "Elodie",
  "Emna",
  "Emy",
  "Erina",
  "Esma",
  "Essia",
  "Essma",
  "Fadela",
  "Fadoua",
  "Fadouma",
  "Fadouzia",
  "Fadwa",
  "Fahima",
  "Fajr",
  "Farah",
  "Farida",
  "Fatiha",
  "Fatima",
  "Fatimae",
  "Fatimazahra",
  "Fawzia",
  "Fayza",
  "Fiza",
  "Ghadir",
  "Ghalia",
  "Ghita",
  "Ghofrane",
  "Ghoufrane",
  "Gihan",
  "Giselle",
  "Hafida",
  "Hafsa",
  "Haifa",
  "Hajar",
  "Hakima",
  "Halima",
  "Hana",
  "Hanaa",
  "Hanane",
  "Hanin",
  "Hasnae",
  "Hassana",
  "Hayat",
  "Hayfa",
  "Heba",
  "Hend",
  "Hiba",
  "Hidaya",
  "Hind",
  "Hindou",
  "Houda",
  "Houdaifa",
  "Houdaissa",
  "Houyem",
  "Huda",
  "Ikbala",
  "Ikram",
  "Ilham",
  "Iliana",
  "Iman",
  "Imane",
  "Imani",
  "Inaya",
  "Ines",
  "Iness",
  "Insaf",
  "Intissar",
  "Intissam",
  "Intissame",
  "Inzha",
  "Islam",
  "Isra",
  "Istabrak",
  "Izdihar",
  "Jamila",
  "Jana",
  "Jannah",
  "Jasmin",
  "Jawhara",
  "Jihane",
  "Jinan",
  "Joory",
  "Kaoutar",
  "Karima",
  "Karimah",
  "Kawtar",
  "Kawthar",
  "Kenza",
  "Khadija",
  "Khadra",
  "Khawla",
  "Khadouj",
  "Khalida",
  "Khawlae",
  "Khmissa",
  "Kiana",
  "Kifah",
  "Laila",
  "Lailae",
  "Lama",
  "Lamiae",
  "Lamiss",
  "Lana",
  "Latifa",
  "Layali",
  "Layal",
  "Layane",
  "Layla",
  "Leila",
  "Lilia",
  "Liliaa",
  "Liliane",
  "Linda",
  "Line",
  "Lina",
  "Lindsay",
  "Loubna",
  "Louisa",
  "Luna",
  "Lylia",
  "Maali",
  "Maissa",
  "Majda",
  "Malak",
  "Maliha",
  "Malika",
  "Manal",
  "Manel",
  "Mariam",
  "Mariem",
  "Marwa",
  "Maryam",
  "Maya",
  "Mayar",
  "Mayda",
  "Mehira",
  "Mehssa",
  "Mennana",
  "Meriem",
  "Meryam",
  "Mesha",
  "Meyssa",
  "Mina",
  "Miryam",
  "Mona",
  "Monia",
  "Mouad",
  "Mounia",
  "Mounira",
  "Mouzah",
  "Mylene",
  "Myriam",
  "Nada",
  "Nadia",
  "Nadira",
  "Nadya",
  "Naela",
  "Nafissa",
  "Nahed",
  "Naima",
  "Naila",
  "Najah",
  "Najet",
  "Najla",
  "Najoua",
  "Najwa",
  "Najat",
  "Nayla",
  "Nawal",
  "Nawel",
  "Nayima",
  "Nazia",
  "Nejma",
  "Nezha",
  "Nihad",
  "Nihal",
  "Nilya",
  "Nisrine",
  "Nissrine",
  "Noha",
  "Nora",
  "Nouhaila",
  "Nouha",
  "Nouhra",
  "Noujoud",
  "Nourelhoda",
  "Nourelhouda",
  "Nour",
  "Noura",
  "Nourhane",
  "Nouria",
  "Nouriya",
  "Nourra",
  "Noury",
  "Nyla",
  "Omaima",
  "Omayma",
  "Oumaima",
  "Oumayma",
  "Oumkeltoum",
  "Qamar",
  "Qistina",
  "Racha",
  "Rafika",
  "Rana",
  "Rania",
  "Ranim",
  "Rashida",
  "Rawan",
  "Rayane",
  "Raziya",
  "Reem",
  "Rehab",
  "Rim",
  "Ritaj",
  "Riyam",
  "Rokia",
  "Rokaya",
  "Roxane",
  "Ruba",
  "Rubaa",
  "Rym",
  "Sabrine",
  "Safae",
  "Safia",
  "Safiya",
  "Sahar",
  "Sahra",
  "Salima",
  "Salma",
  "Salome",
  "Salwa",
  "Samaa",
  "Samah",
  "Samia",
  "Samira",
  "Sana",
  "Sanaa",
  "Sanaya",
  "Sarah",
  "Sarhane",
  "Sarra",
  "Sawsen",
  "Sayeda",
  "Sawsan",
  "Selma",
  "Selsabil",
  "Shaima",
  "Shams",
  "Shanza",
  "Shatha",
  "Sheryne",
  "Shifa",
  "Shukriya",
  "Sihem",
  "Sirine",
  "Sofia",
  "Soha",
  "Souad",
  "Soukaina",
  "Soumaya",
  "Soumia",
  "Soumya",
  "Suzanne",
  "Tala",
  "Tamara",
  "Tanina",
  "Taqwa",
  "Tasnim",
  "Thana",
  "Wafae",
  "Wafiya",
  "Waha",
  "Wala",
  "Widad",
  "Wijdan",
  "Wissal",
  "Wissem",
  "Yamina",
  "Yamila",
  "Yana",
  "Yara",
  "Yasira",
  "Yasmeen",
  "Yasmina",
  "Yasmine",
  "Yassmine",
  "Yousra",
  "Yumna",
  "Yusra",
  "Zahira",
  "Zahirah",
  "Zahra",
  "Zaida",
  "Zakia",
  "Zaynab",
  "Zeinab",
  "Zena",
  "Zeroual",
  "Zineb",
  "Zohra",
  "Zohre",
  "Zuhra",
  "Zuhura",
  "Zyneb",
  "Aya Zahra",
  "Aya Lina",
  "Aya Noor",
  "Aya Amal",
  "Aya Aya",
  "Aya Sara",
  "Aya Lamia",
  "Aya Lilia",
  "Aya Meriem",
  "Aya Yousra",
  "Aya Maryam",
  "Aya Imane",
  "Aya Salma",
  "Aya Sabrine",
  "Aya Soukaina",
  "Aya Malika",
  "Aya Ikram",
  "Aya Ines",
  "Aya Kawtar",
  "Aya Yasmine",
  "Aya Anissa",
  "Aya Afaf",
  "Aya Wiam",
  "Aya Wissem",
  "Aya Loubna",
  "Aya Najwa",
  "Aya Najla",
  "Aya Nisrine",
  "Aya Siham",
  "Aya Samira",
  "Aya Latifa",
  "Aya Rania",
  "Aya Farah",
  "Aya Samia",
  "Aya Nadia",
  "Aya Sabah",
  "Aya Safae",
  "Aya Sanae",
  "Aya Sarra",
  "Aya Sihame",
  "Aya Ikbala",
  "Aya Chaima",
  "Aya Malak",
  "Aya Mouna",
  "Aya Rajae",
  "Aya Najiba",
  "Aya Batoul",
  "Aya Linae",
  "Aya Noura",
  "Aya Mounia",
  "Sara Zahra",
  "Sara Lina",
  "Sara Noor",
  "Sara Amal",
  "Sara Aya",
  "Sara Sara",
  "Sara Lamia",
  "Sara Lilia",
  "Sara Meriem",
  "Sara Yousra",
  "Sara Maryam",
  "Sara Imane",
  "Sara Salma",
  "Sara Sabrine",
  "Sara Soukaina",
  "Sara Malika",
  "Sara Ikram",
  "Sara Ines",
  "Sara Kawtar",
  "Sara Yasmine",
  "Sara Anissa",
  "Sara Afaf",
  "Sara Wiam",
  "Sara Wissem",
  "Sara Loubna",
  "Sara Najwa",
  "Sara Najla",
  "Sara Nisrine",
  "Sara Siham",
  "Sara Samira",
  "Sara Latifa",
  "Sara Rania",
  "Sara Farah",
  "Sara Samia",
  "Sara Nadia",
  "Sara Sabah",
  "Sara Safae",
  "Sara Sanae",
  "Sara Sarra",
  "Sara Sihame",
  "Sara Ikbala",
  "Sara Chaima",
  "Sara Malak",
  "Sara Mouna",
  "Sara Rajae",
  "Sara Najiba",
  "Sara Batoul",
  "Sara Linae",
  "Sara Noura",
  "Sara Mounia",
  "Lina Zahra",
  "Lina Lina",
  "Lina Noor",
  "Lina Amal",
  "Lina Aya",
  "Lina Sara",
  "Lina Lamia",
  "Lina Lilia",
  "Lina Meriem",
  "Lina Yousra",
  "Lina Maryam",
  "Lina Imane",
  "Lina Salma",
  "Lina Sabrine",
  "Lina Soukaina",
  "Lina Malika",
  "Lina Ikram",
  "Lina Ines",
  "Lina Kawtar",
  "Lina Yasmine",
  "Lina Anissa",
  "Lina Afaf",
  "Lina Wiam",
  "Lina Wissem",
  "Lina Loubna",
  "Lina Najwa",
  "Lina Najla",
  "Lina Nisrine",
  "Lina Siham",
  "Lina Samira",
  "Lina Latifa",
  "Lina Rania",
  "Lina Farah",
  "Lina Samia",
  "Lina Nadia",
  "Lina Sabah",
  "Lina Safae",
  "Lina Sanae",
  "Lina Sarra",
  "Lina Sihame",
  "Lina Ikbala",
  "Lina Chaima",
  "Lina Malak",
  "Lina Mouna",
  "Lina Rajae",
  "Lina Najiba",
  "Lina Batoul",
  "Lina Linae",
  "Lina Noura",
  "Lina Mounia",
  "Malak Zahra",
  "Malak Lina",
  "Malak Noor",
  "Malak Amal",
  "Malak Aya",
  "Malak Sara",
  "Malak Lamia",
  "Malak Lilia",
  "Malak Meriem",
  "Malak Yousra",
  "Malak Maryam",
  "Malak Imane",
  "Malak Salma",
  "Malak Sabrine",
  "Malak Soukaina",
  "Malak Malika",
  "Malak Ikram",
  "Malak Ines",
  "Malak Kawtar",
  "Malak Yasmine",
  "Malak Anissa",
  "Malak Afaf",
  "Malak Wiam",
  "Malak Wissem",
  "Malak Loubna",
  "Malak Najwa",
  "Malak Najla",
  "Malak Nisrine",
  "Malak Siham",
  "Malak Samira",
  "Malak Latifa",
  "Malak Rania",
  "Malak Farah",
  "Malak Samia",
  "Malak Nadia",
  "Malak Sabah",
  "Malak Safae",
  "Malak Sanae",
  "Malak Sarra",
  "Malak Sihame",
  "Malak Ikbala",
  "Malak Chaima",
  "Malak Malak",
  "Malak Mouna",
  "Malak Rajae",
  "Malak Najiba",
  "Malak Batoul",
  "Malak Linae",
  "Malak Noura",
  "Malak Mounia",
  "Noor Zahra",
  "Noor Lina",
  "Noor Noor",
  "Noor Amal",
  "Noor Aya",
  "Noor Sara",
  "Noor Lamia",
  "Noor Lilia",
  "Noor Meriem",
  "Noor Yousra",
  "Noor Maryam",
  "Noor Imane",
  "Noor Salma",
  "Noor Sabrine",
  "Noor Soukaina",
  "Noor Malika",
  "Noor Ikram",
  "Noor Ines",
  "Noor Kawtar",
  "Noor Yasmine",
  "Noor Anissa",
  "Noor Afaf",
  "Noor Wiam",
  "Noor Wissem",
  "Noor Loubna",
  "Noor Najwa",
  "Noor Najla",
  "Noor Nisrine",
  "Noor Siham",
  "Noor Samira",
  "Noor Latifa",
  "Noor Rania",
  "Noor Farah",
  "Noor Samia",
  "Noor Nadia",
  "Noor Sabah",
  "Noor Safae",
  "Noor Sanae",
  "Noor Sarra",
  "Noor Sihame",
  "Noor Ikbala",
  "Noor Chaima",
  "Noor Malak",
  "Noor Mouna",
  "Noor Rajae",
  "Noor Najiba",
  "Noor Batoul",
  "Noor Linae",
  "Noor Noura",
  "Noor Mounia",
  "Yasmina Zahra",
  "Yasmina Lina",
  "Yasmina Noor",
  "Yasmina Amal",
  "Yasmina Aya",
  "Yasmina Sara",
  "Yasmina Lamia",
  "Yasmina Lilia",
  "Yasmina Meriem",
  "Yasmina Yousra",
  "Yasmina Maryam",
  "Yasmina Imane",
  "Yasmina Salma",
  "Yasmina Sabrine",
  "Yasmina Soukaina",
  "Yasmina Malika",
  "Yasmina Ikram",
  "Yasmina Ines",
  "Yasmina Kawtar",
  "Yasmina Yasmine",
  "Yasmina Anissa",
  "Yasmina Afaf",
  "Yasmina Wiam",
  "Yasmina Wissem",
  "Yasmina Loubna",
  "Yasmina Najwa",
  "Yasmina Najla",
  "Yasmina Nisrine",
  "Yasmina Siham",
  "Yasmina Samira",
  "Yasmina Latifa",
  "Yasmina Rania",
  "Yasmina Farah",
  "Yasmina Samia",
  "Yasmina Nadia",
  "Yasmina Sabah",
  "Yasmina Safae",
  "Yasmina Sanae",
  "Yasmina Sarra",
  "Yasmina Sihame",
  "Yasmina Ikbala",
  "Yasmina Chaima",
  "Yasmina Malak",
  "Yasmina Mouna",
  "Yasmina Rajae",
  "Yasmina Najiba",
  "Yasmina Batoul",
  "Yasmina Linae",
  "Yasmina Noura",
  "Yasmina Mounia",
  "Hiba Zahra",
  "Hiba Lina",
  "Hiba Noor",
  "Hiba Amal",
  "Hiba Aya",
  "Hiba Sara",
  "Hiba Lamia",
  "Hiba Lilia",
  "Hiba Meriem",
  "Hiba Yousra",
  "Hiba Maryam",
  "Hiba Imane",
  "Hiba Salma",
  "Hiba Sabrine",
  "Hiba Soukaina",
  "Hiba Malika",
  "Hiba Ikram",
  "Hiba Ines",
  "Hiba Kawtar",
  "Hiba Yasmine",
  "Hiba Anissa",
  "Hiba Afaf",
  "Hiba Wiam",
  "Hiba Wissem",
  "Hiba Loubna",
  "Hiba Najwa",
  "Hiba Najla",
  "Hiba Nisrine",
  "Hiba Siham",
  "Hiba Samira",
  "Hiba Latifa",
  "Hiba Rania",
  "Hiba Farah",
  "Hiba Samia",
  "Hiba Nadia",
  "Hiba Sabah",
  "Hiba Safae",
  "Hiba Sanae",
  "Hiba Sarra",
  "Hiba Sihame",
  "Hiba Ikbala",
  "Hiba Chaima",
  "Hiba Malak",
  "Hiba Mouna",
  "Hiba Rajae",
  "Hiba Najiba",
  "Hiba Batoul",
  "Hiba Linae",
  "Hiba Noura",
  "Hiba Mounia",
  "Amina Zahra",
  "Amina Lina",
  "Amina Noor",
  "Amina Amal",
  "Amina Aya",
  "Amina Sara",
  "Amina Lamia",
  "Amina Lilia",
  "Amina Meriem",
  "Amina Yousra",
  "Amina Maryam",
  "Amina Imane",
  "Amina Salma",
  "Amina Sabrine",
  "Amina Soukaina",
  "Amina Malika",
  "Amina Ikram",
  "Amina Ines",
  "Amina Kawtar",
  "Amina Yasmine",
  "Amina Anissa",
  "Amina Afaf",
  "Amina Wiam",
  "Amina Wissem",
  "Amina Loubna",
  "Amina Najwa",
  "Amina Najla",
  "Amina Nisrine",
  "Amina Siham",
  "Amina Samira",
  "Amina Latifa",
  "Amina Rania",
  "Amina Farah",
  "Amina Samia",
  "Amina Nadia",
  "Amina Sabah",
  "Amina Safae",
  "Amina Sanae",
  "Amina Sarra",
  "Amina Sihame",
  "Amina Ikbala",
  "Amina Chaima",
  "Amina Malak",
  "Amina Mouna",
  "Amina Rajae",
  "Amina Najiba",
  "Amina Batoul",
  "Amina Linae",
  "Amina Noura",
  "Amina Mounia",
  "Mariam Zahra",
  "Mariam Lina",
  "Mariam Noor",
  "Mariam Amal",
  "Mariam Aya",
  "Mariam Sara",
  "Mariam Lamia",
  "Mariam Lilia",
  "Mariam Meriem",
  "Mariam Yousra",
  "Mariam Maryam",
  "Mariam Imane",
  "Mariam Salma",
  "Mariam Sabrine",
  "Mariam Soukaina",
  "Mariam Malika",
  "Mariam Ikram",
  "Mariam Ines",
  "Mariam Kawtar",
  "Mariam Yasmine",
  "Mariam Anissa",
  "Mariam Afaf",
  "Mariam Wiam",
  "Mariam Wissem",
  "Mariam Loubna",
  "Mariam Najwa",
  "Mariam Najla",
  "Mariam Nisrine",
  "Mariam Siham",
  "Mariam Samira",
  "Mariam Latifa",
  "Mariam Rania",
  "Mariam Farah",
  "Mariam Samia",
  "Mariam Nadia",
  "Mariam Sabah",
  "Mariam Safae",
  "Mariam Sanae",
  "Mariam Sarra",
  "Mariam Sihame",
  "Mariam Ikbala",
  "Mariam Chaima",
  "Mariam Malak",
  "Mariam Mouna",
  "Mariam Rajae",
  "Mariam Najiba",
  "Mariam Batoul",
  "Mariam Linae",
  "Mariam Noura",
  "Mariam Mounia",
  "Salma Zahra",
  "Salma Lina",
  "Salma Noor",
  "Salma Amal",
  "Salma Aya",
  "Salma Sara",
  "Salma Lamia",
  "Salma Lilia",
  "Salma Meriem",
  "Salma Yousra",
  "Salma Maryam",
  "Salma Imane",
  "Salma Salma",
  "Salma Sabrine",
  "Salma Soukaina",
  "Salma Malika",
  "Salma Ikram",
  "Salma Ines",
  "Salma Kawtar",
  "Salma Yasmine",
  "Salma Anissa",
  "Salma Afaf",
  "Salma Wiam",
  "Salma Wissem",
  "Salma Loubna",
  "Salma Najwa",
  "Salma Najla",
  "Salma Nisrine",
  "Salma Siham",
  "Salma Samira",
  "Salma Latifa",
  "Salma Rania",
  "Salma Farah",
  "Salma Samia",
  "Salma Nadia",
  "Salma Sabah",
  "Salma Safae",
  "Salma Sanae",
  "Salma Sarra",
  "Salma Sihame",
  "Salma Ikbala",
  "Salma Chaima",
  "Salma Malak",
  "Salma Mouna",
  "Salma Rajae",
  "Salma Najiba",
  "Salma Batoul",
  "Salma Linae",
  "Salma Noura",
  "Salma Mounia",
  "Imane Zahra",
  "Imane Lina",
  "Imane Noor",
  "Imane Amal",
  "Imane Aya",
  "Imane Sara",
  "Imane Lamia",
  "Imane Lilia",
  "Imane Meriem",
  "Imane Yousra",
  "Imane Maryam",
  "Imane Imane",
  "Imane Salma",
  "Imane Sabrine",
  "Imane Soukaina",
  "Imane Malika",
  "Imane Ikram",
  "Imane Ines",
  "Imane Kawtar",
  "Imane Yasmine",
  "Imane Anissa",
  "Imane Afaf",
  "Imane Wiam",
  "Imane Wissem",
  "Imane Loubna",
  "Imane Najwa",
  "Imane Najla",
  "Imane Nisrine",
  "Imane Siham",
  "Imane Samira",
  "Imane Latifa",
  "Imane Rania",
  "Imane Farah",
  "Imane Samia",
  "Imane Nadia",
  "Imane Sabah",
  "Imane Safae",
  "Imane Sanae",
  "Imane Sarra",
  "Imane Sihame",
  "Imane Ikbala",
  "Imane Chaima",
  "Imane Malak",
  "Imane Mouna",
  "Imane Rajae",
  "Imane Najiba",
  "Imane Batoul",
  "Imane Linae",
  "Imane Noura",
  "Imane Mounia",
  "Rania Zahra",
  "Rania Lina",
  "Rania Noor",
  "Rania Amal",
  "Rania Aya",
  "Rania Sara",
  "Rania Lamia",
  "Rania Lilia",
  "Rania Meriem",
  "Rania Yousra",
  "Rania Maryam",
  "Rania Imane",
  "Rania Salma",
  "Rania Sabrine",
  "Rania Soukaina",
  "Rania Malika",
  "Rania Ikram",
  "Rania Ines",
  "Rania Kawtar",
  "Rania Yasmine",
  "Rania Anissa",
  "Rania Afaf",
  "Rania Wiam",
  "Rania Wissem",
  "Rania Loubna",
  "Rania Najwa",
  "Rania Najla",
  "Rania Nisrine",
  "Rania Siham",
  "Rania Samira",
  "Rania Latifa",
  "Rania Rania",
  "Rania Farah",
  "Rania Samia",
  "Rania Nadia",
  "Rania Sabah",
  "Rania Safae",
  "Rania Sanae",
  "Rania Sarra",
  "Rania Sihame",
  "Rania Ikbala",
  "Rania Chaima",
  "Rania Malak",
  "Rania Mouna",
  "Rania Rajae",
  "Rania Najiba",
  "Rania Batoul",
  "Rania Linae",
  "Rania Noura",
  "Rania Mounia",
  "Nada Zahra",
  "Nada Lina",
  "Nada Noor",
  "Nada Amal",
  "Nada Aya",
  "Nada Sara",
  "Nada Lamia",
  "Nada Lilia",
  "Nada Meriem",
  "Nada Yousra",
  "Nada Maryam",
  "Nada Imane",
  "Nada Salma",
  "Nada Sabrine",
  "Nada Soukaina",
  "Nada Malika",
  "Nada Ikram",
  "Nada Ines",
  "Nada Kawtar",
  "Nada Yasmine",
  "Nada Anissa",
  "Nada Afaf",
  "Nada Wiam",
  "Nada Wissem",
  "Nada Loubna",
  "Nada Najwa",
  "Nada Najla",
  "Nada Nisrine",
  "Nada Siham",
  "Nada Samira",
  "Nada Latifa",
  "Nada Rania",
  "Nada Farah",
  "Nada Samia",
  "Nada Nadia",
  "Nada Sabah",
  "Nada Safae",
  "Nada Sanae",
  "Nada Sarra",
  "Nada Sihame",
  "Nada Ikbala",
  "Nada Chaima",
  "Nada Malak",
  "Nada Mouna",
  "Nada Rajae",
  "Nada Najiba",
  "Nada Batoul",
  "Nada Linae",
  "Nada Noura",
  "Nada Mounia",
  "Hajar Zahra",
  "Hajar Lina",
  "Hajar Noor",
  "Hajar Amal",
  "Hajar Aya",
  "Hajar Sara",
  "Hajar Lamia",
  "Hajar Lilia",
  "Hajar Meriem",
  "Hajar Yousra",
  "Hajar Maryam",
  "Hajar Imane",
  "Hajar Salma",
  "Hajar Sabrine",
  "Hajar Soukaina",
  "Hajar Malika",
  "Hajar Ikram",
  "Hajar Ines",
  "Hajar Kawtar",
  "Hajar Yasmine",
  "Hajar Anissa",
  "Hajar Afaf",
  "Hajar Wiam",
  "Hajar Wissem",
  "Hajar Loubna",
  "Hajar Najwa",
  "Hajar Najla",
  "Hajar Nisrine",
  "Hajar Siham",
  "Hajar Samira",
  "Hajar Latifa",
  "Hajar Rania",
  "Hajar Farah",
  "Hajar Samia",
  "Hajar Nadia",
  "Hajar Sabah",
  "Hajar Safae",
  "Hajar Sanae",
  "Hajar Sarra",
  "Hajar Sihame",
  "Hajar Ikbala",
  "Hajar Chaima",
  "Hajar Malak",
  "Hajar Mouna",
  "Hajar Rajae",
  "Hajar Najiba",
  "Hajar Batoul",
  "Hajar Linae",
  "Hajar Noura",
  "Hajar Mounia",
  "Ghita Zahra",
  "Ghita Lina",
  "Ghita Noor",
  "Ghita Amal",
  "Ghita Aya",
  "Ghita Sara",
  "Ghita Lamia",
  "Ghita Lilia",
  "Ghita Meriem",
  "Ghita Yousra",
  "Ghita Maryam",
  "Ghita Imane",
  "Ghita Salma",
  "Ghita Sabrine",
  "Ghita Soukaina",
  "Ghita Malika",
  "Ghita Ikram",
  "Ghita Ines",
  "Ghita Kawtar",
  "Ghita Yasmine",
]

export function getRandomNames(excludedNamesSet = new Set(), count = 10) {
  const excluded = excludedNamesSet || new Set();
  const pool = girlNames.filter((name) =>
    !excluded.has(name.toLowerCase().trim())
  );
  if (!pool.length) {
    return [];
  }
  const picks = new Set();
  while (picks.size < Math.min(count, pool.length)) {
    const choice = pool[Math.floor(Math.random() * pool.length)];
    picks.add(choice);
    if (picks.size === pool.length) {
      break;
    }
  }
  return Array.from(picks);
}
